name: LunarskyInstance
version: 1.0
main: de.lunarsky.rewardinstance.core.RewardInstancePlugin

api-version: 1.21
depends: [Multiverse-Core, FastAsyncWorldEdit, VoidGen]
softdepend: [PlaceholderAPI]
author: treppi / plscomeback

libraries:
  - com.squareup.okhttp3:okhttp:4.9.0

commands:
  givekey:
    description: gives a player the item to enter a dungeon
  addsplinter:
    description: adds a splinter to a player if they can hold more
  peekloot:
    descriptions: drops all the loot to review it.
  guesssplinter:
    description: 27% chance to get a splinter
  crystals:
    description: View how many crystals you have
    aliases:
      - "kristalle"
      - "meteoritenkristalle"
      - "meteoriten"
      - "kristall"
      - "splitter"